name: Release mosdns docker
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: |
        echo "TAG=$(cat tag)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          REPOSITORY=IrineSistiana/mosdns
          TAG=${{ env.TAG }}
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ghcr.io/guhill1/mosdns:latest
          ghcr.io/guhill1/mosdns:${{ env.TAG }}
